@startuml ER_Diagram_CoreServices

title ER-диаграмма для ключевых сервисов

package "Registry Service" {

' Пользователи
entity "Users" {
  ' Уникальный идентификатор, синхронизируется с Users Service
  * id: UUID <<PK>>
  --
  ' Отображаемое имя, используется в интерфейсах поддержки
  * display_name: varchar
}

' Дома
entity "Houses" {
  ' Уникальный идентификатор дома
  * id: UUID <<PK>>
  --
  ' Отображаемое имя (например, "Дача")
  * display_name: varchar
  ' Внешний ключ на владельца дома
  # user_id: UUID <<FK>>
}

' Устройства
entity "Devices" {
  ' Уникальный идентификатор устройства
    * id: UUID <<PK>>
    --
  ' Отображаемое имя (например, "Нагреватель в спальне")
    * display_name: varchar
  ' Серийный номер производителя
    * serial_number: varchar
  ' Вендор (по хорошему справочник, но упростим)
    * vendor: varchar
  ' Статус (включен, выключен, поломался)
    * status: varchar ' (online, offline, error)
  ' Дополнительные свойства
    properties: jsonb
  ' Уроверь батареи, в процентах
    battery_level: integer
  ' Внешний ключ на дом
    # house_id: UUID <<FK>>
  ' Внешний ключ на тип устройства
    # device_type_id: integer <<FK>>
  }

' Типы устройств
entity "DeviceTypes" {
  ' Уникальный идентификатор типа устройства
    * id: integer <<PK>>
    --
  ' Имя 
    * name: varchar ' ("Датчик температуры", "Умная розетка")
    description: text
  }


' У одного пользователя может быть 0 или больше домов
  Users ||--o{ Houses
' В доме может не быть устройств (ил ибыть много)
  Houses ||--o{ Devices
' Мы можем знать о типе устройств, но их пока нет
  DeviceTypes ||--o{ Devices
}

package "Automation Service" {

' Сценарии
entity "Scenarios" {
' Идентификатор сценария    
  * id: UUID <<PK>>
    --
' Идентификатор пользователя, синхронизируется с Users Service
  * user_id: UUID
' Человекочитаемое наименование сценария
  * name: varchar
' Сценарий активен или приостановлен (enum более расширяемо, чем просто ищщдуфт)
  * status: ' (enabled, disabled)
}

' Атрибуты устройств (температура, влажность)
entity "DeviceAttributes" {
  ' Уникальный идентификатор атрибута
    * id: integer <<PK>>
    --
  ' Имя 
    * name: varchar ' ("Температура", "Влажность")
    description: text
  }


' Триггеры (на что реагируем)
entity "Triggers" {
' Идентификатор триггера
  * id: UUID <<PK>>
  --
' На какое устройство реагируем (не внешний ключ, таблицы устройств тут не будет, будет ходить за метаданными чере API)    
  * source_device_id: UUID 
' На какое его свойство? Например, "Температура"  
  # device_attribute_id: integer <<FK>>
' Триггер связан со сценарием
  # scenario_id: UUID <<FK>>
}

  ' Один атрибут может использоваться во многих триггерах
  DeviceAttributes ||--o{ Triggers
' У одного сценария может быть один или несколько триггеров
  Scenarios ||--o{ Triggers

}



@enduml